GET http://localhost:3000/transacoes

###

GET http://localhost:3000/insights

###

GET http://localhost:3000/resumo

###

POST http://localhost:3000/transacoes
Content-Type: application/json

{
  "descricao": "Nuggets",
  "categoria": "Eletrônicos",
  "valor": 14,
  "tipo": "saida",
  "metodo_pagamento": "pix",
  "observacao": "Compra da Semana"
}
###

DELETE http://localhost:3000/transacoes/1

###

PUT http://localhost:3000/transacoes/6
Content-Type: application/json

{
  "descricao": "Nuggets",
  "categoria": "Comida",
  "valor": 14,
  "tipo": "saida",
  "metodo_pagamento": "pix",
  "observacao": "Salário atualizado"
}

###

GET http://localhost:3000/gasto-categoria

###

GET http://localhost:3000/media-mensal

###

GET http://localhost:3000/maior-gasto

###

GET http://localhost:3000/menor-gasto

###

GET http://localhost:3000/variacao-mensal

###

GET http://localhost:3000/transacoes/periodo?dataInicio=2026-04-27&dataFim=2026-04-29

###

GET http://localhost:3000/transacoes/categoria?categoria=Eletrônicos

###

GET http://localhost:3000/transacoes/tipo?tipo=saida

###

GET http://localhost:3000/transacoes/valor?min=100&max=1000

###

GET http://localhost:3000/dashboard
